# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 972d6ea25fd160a826454e39e61240bd8208a81220b1eb319a80c86e821ac3d6a89e6ffc0f96606cbbc3d8468fc41007085274310c834b6be92b01ea4486d744

test:
  secret_key_base: 027bb0a85fe1fca0a952ee2e21e640298a702d26280e318973c5ff6420c03dd748a1d44a01af4351995f0f72c03457c6ef962c998f7622a7b5e01d81bcbf624c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
